# A list of any common terminal packages I reach for.

[git]
ubuntu = "apt:git"

[vim]
ubuntu = "apt:vim"

[curl]
ubuntu = "apt:curl"

[wget]
ubuntu = "apt:wget"

[neofetch]
ubuntu = "apt:neofetch"

[fzf]
ubuntu = "apt:fzf"

[ripgrep]
ubuntu = "apt:ripgrep"

[htop]
ubuntu = "apt:htop"

[jq]
ubuntu = "apt:jq"

[bat]
ubuntu = "gh-release:https://github.com/sharkdp/bat/releases"

[delta]
ubuntu = "gh-release:https://github.com/dandavison/delta/releases"

[dnote]
ubuntu = "gh-release:https://github.com/dnote/dnote/releases"
